[[health-check-service]]
= HealthCheck Service

_Since Payara Server 4.1.1.161_

Payara Server Enterprise includes a HealthCheck Service that is disabled by default.
When enabled it can periodically check the following performance metrics:

* Host CPU Usage
* Host Memory Usage
* Payara Server’s JVM Garbage Collections
* Payara Server’s JVM Heap Usage
* CPU Usage of individual threads
* Detects stuck threads
* Monitors metrics exposed by MicroProfile Metrics

If there is a problem with any of these metrics and they exceed a
configurable threshold then a `GOOD`, `WARNING` or `CRITICAL` event
notification is sent to the Notification Service. Notifications can be then sent
to one or more notifiers, e.g. a log file.

This allows operations teams to rapidly detect problems or work out what happened after these
problems have occurred.

NOTE: Since Payara Server 5.26.0 it is possible to display metrics produced by HealthCheck service on MicroProfile Health xref:/documentation/microprofile/healthcheck.adoc#rest-endpoints[REST endpoints]. You can find more information on xref:/documentation/payara-server/health-check-service/asadmin-commands.adoc#set-healthcheck-service-configuration[set-healthcheck-service-configuration].

NOTE: The Host Memory Usage currently only works on Linux and BSD derivatives.

If the
xref:/documentation/payara-server/notification-service/notifiers/log-notifier.adoc[Log Notifier]
is enabled, such events will be presented in the server's log file like in the
following sample:

[source, log]
----
[2016-05-24T03:52:28.690+0000] [Payara 4.1] [INFO] [fish.payara.nucleus.healthcheck.HealthCheckService] [tid: _ThreadID=72 _ThreadName=healthcheck-service-3 [timeMillis: 1464061948690] [levelValue: 800] [[ CPUC:Health Check Result:[[status=WARNING, message='CPU%: 75.6, Time CPU used: 267 milliseconds'']']]]  [2016-05-24T21:11:36.579+0000] [Payara 4.1] [SEVERE] [fish.payara.nucleus.healthcheck.HealthCheckService] [tid: _ThreadID=71 _ThreadName=healthcheck-service-3] [timeMillis: 1464124296579] [levelValue: 1000] [[ HOGT:Health Check Result:[[status=CRITICAL, message='Thread with <id-name>: 145-testing-thread-1 is a hogging thread for the last 59 seconds 999 milliseconds'']']]] 
----
