[[advanced-jdbc-configuration-and-diagnostics.]]
= Advanced JDBC Configuration and Diagnostics

_Since Payara Server 4.1.1.161 and Payara Server Micro 4.1.1.161_

Payara Server and Payara Micro 161 comes integrated with new
capabilities for advanced JDBC connection pool configuration and
diagnostics.

Many performance problems in Enterprise Applications can be traced to
slow database access or database connectivity problems. To help prevent
and diagnose database access problems new powerful features have been
introduced.

[[slow-sql-logging]]
== Slow SQL Logging

Connection pools can be configured to log a warning whenever a database
query exceeds a defined threshold. This enables your operations team to
rapidly diagnose performance problems and identify poorly performing
SQL.

See xref:slow-sql-logger.adoc[Slow-SQL-Logger] for detailed information.

[[full-jdbc-tracing]]
== Full JDBC Tracing

Connection pools can be configured to log all JDBC calls made to the
connection pool including the SQL statements and its execution time
of the call. This is especially useful in development to understand
the SQL generated via frameworks like JPA and see what the performance
characteristics look like. As the tracing is done at the connection
pool level all direct SQL or other data access technologies are captured.

See xref:log-jdbc-calls.adoc[Log-JDBC-Calls] for detailed information.

[[sql-trace-listeners]]
== SQL Trace Listeners

It is also possible to use the Payara Server APIs used to implement both
the Payara Server Slow SQL Logging and JDBC tracing capabilities to
create custom diagnostic and tracing functionality via *SQL Trace
Listeners*.

See xref:sql-trace-listeners.adoc[SQL Trace Listeners] for detailed
Information.

[[advanced-connection-pool-configuration-properties]]
== Advanced Connection pool Configuration Properties

All connection pool properties available on the administration console
for Payara Server global data sources can now be configured on
application scoped data sources deployed via deployment descriptors or
annotations.

See xref:advanced-connection-pool-properties.adoc[Advanced Connection Pool
Properties] for detailed information.

[[jdbc-connection-validation-changes]]
== JDBC Connection Validation Changes

See the xref:/documentation/payara-server/jdbc/jdbc-connection-validation.adoc[JDBC Connection Validation page]
in the core documentation for information on changes between GlassFish Server
and Payara Server's *JDBC Connection Validation*.
