[[notifiers]]
= Notifiers

The notification service comes with an integrated set of notifiers that
can be used to send notification events to a distinct variety of
channels apart from the standard server log mechanism:

*CDI Event Bus*:: For sending notification events using xref:/documentation/payara-server/public-api/cdi-events.adoc[Payara's CDI Event Bus]
 and observing them in instances in the cluster.
*Datadog*:: Allows sending notification events to the *Datadog* monitoring service.
*Discord*:: Allows sending notification events to *Discord* webhooks.
*Email*:: Taking advantage of preconfigured Java Mail sessions in the
server, you can route notifications to an email account.
*Event Bus*:: Uses Hazelcast to send notifications into the internal Payara event bus based on Hazelcast distributed topics.
*JMS*:: Taking advantage of preconfigured JMS connection resources, you
can route notifications to a Java Message Queue so it can be consumed by
other applications or services.
*Slack*:: Allows sending notification events to a specific *Slack* channel
*SNMP*:: Allows monitoring servers to scout for notification events
using SNMP traps.
*Teams*:: Allows sending notification events to *Microsoft Teams* webhooks.
*XMPP*:: Allows sending notification events to XMPP servers.
*NewRelic*:: Allows sending notification events to a *NewRelic* service account.

Appropriate instructions on how to configure and use all of these
notification mechanisms are included in this section.

[[removing-notifiers]]
== `Removing Notifiers`
All Payara notifiers are included in Payara Enterprise by default, however they are fully pluggable and can be removed from your Payara installation. Each notifier consists of 2 parts, a notifier-core and a notifier-console-plugin. The notifier core is responsible for the notifier functionality and the asadmin commands, the notifier-console-plugin is not essential, but allows for the notifier to be configured through the admin console.

To remove a notifier from Payara Enterprise edition, first find the relevant modules to the notifier you want to remove in `${PAYARA_HOME}/glassfish/modules`. To fully remove the notifier, you should delete both the notifier-core and the notifier-console-plugin files, then restart the domain.

If you change your mind in the future, you can just drop both the notifier-core and optionally the notifier-console-plugin files back into the `${PAYARA_HOME}/glassfish/modules` directory and restart the domain.