[[configurable-jsf-options]]
= Configurable JSF options

_Since Payara Server 5.182_

It is possible to specify a Payara specific JSF context parameter in `web.xml`, named `fish.payara.faces.enableParallelInit`.

[[usage]]
== Usage

When the `fish.payara.faces.enableParallelInit` context parameter is set to `true` some of the internal initialisation of Mojarra (the JSF implementation Payara uses) is performed in parallel. For this the platform fork/join thread pool is used, which is the same pool used for processing JDK 8 Streams in parallel.

[[usage-example]]
=== Example

Here's an example that sets the option to `true` in `web.xml`:

[source, xml]
----
<context-param>
    <param-name>fish.payara.faces.enableParallelInit</param-name>
    <param-value>true</param-value>
</context-param>
----

[[note]]
=== Note

The `fish.payara.faces.enableParallelInit` context parameter can be combined with the `com.sun.faces.enableThreading` one:

[source, xml]
----
<context-param>
    <param-name>com.sun.faces.enableThreading</param-name>
    <param-value>true</param-value>
</context-param>
----

This is an existing (non Payara specific) parameter to also enable parallel initialisation, but in a slightly earlier stage of the initialisation process. As an Payara Platform specific implementation  this will use the Platform Concurrency executor if there is one, if not it will create a single use executor with 5 threads.



