[[ssl-certificates]]
= Configure SSL Certificates

The Payara Server Enterprise uses a dedicated key and certificate store when using SSL/TLS connections. The files are located in the configuration directory of the domain `<payara-home>/glassfish/domains/<domain-name>/config` and referenced through JVM options so that they are used for the entire JVM.

_cacerts.jks_: Java Keystore formatted file used as Trust Store file holding the X.509 certificates.
_keystore.jks_: Java Keystore formatted file containing the Cryptographic keys, like the private keys associated with the certificates.

These keystores are protected with the Master Password of your domain.

[[add-certificate]]
== Adding SSL Certificate

To add your SSL Certificate to the Payara Server configuration files, you need:

- The private key associated with your certificate.
- The Certificate you received from the Certificate Authority based on your Certificate Signing Request (CSR).

You can generate a self-signed certificate using the command detailed
xref:documentation/payara-server/server-configuration/certificate-management.adoc#generate-self-signed-certificate[here]

[source,shell]
----
asadmin generate-self-signed-certificate --dn "CN=test.payara.fish,IP=127.0.0.1" mydomain_certificate
----

*Alternatively*::
You can find the detailed steps of adding a self-signed certificate into Payara Server Enterprise for testing purposes using keytool and openssl in the blog https://blog.payara.fish/securing-payara-server-with-custom-ssl-certificate[Securing Payara Server with Custom SSL Certificate].
The private key can be stored in various formats. We assume that the key is in a format which can be read by the Java key tool program, such as PKCS#8 (file starts with `BEGIN ENCRYPTED PRIVATE KEY`)

In a first step (if following the blog), we combine the Private key and the Certificate we received into a file.  This file can then be used to merge our data into the files used by the Payara installation.
In this step, we also specify an alias name for our key/certificate. This alias name is important as we will use it later to refer to our specific SSL Certificate.

The command to perform this combination is the following with OpenSSL:

[source,shell]
----
openssl pkcs12 -export -in mycert.crt -inkey mycert.key -out mycert.p12 -name mydomain_certificate
----

The resulting p12 bundle can then be add to the keystore and trutstore in Payara Server as described in the following sections.

=== Import into keystore.jks

The information needs to be imported into the _keystore.jks_ file of your Payara Server Domain which will use it.

This is performed using the `add-to-keystore` asadmin command, detailed
xref:documentation/payara-server/server-configuration/certificate-management.adoc#add-to-keystore[here].

[source,shell]
----
asadmin add-to-keystore --file mycert.p12 mydomain_certificate
----

*Alternatively*::
You can also use the _keytool_ command of the JDK:

[source,shell]
----
keytool -importkeystore -destkeystore keystore.jks -srckeystore mycert.p12 -srcstoretype PKCS12 -alias mydomain_certificate
----

The parameters of the above command are self-explanatory. Important here is the correct alias value.

=== Import into cacerts.jks

A similar command is used to import the information into the Trust Store file so that our certificate is trusted by the JVM.

This is performed using the `add-to-truststore` asadmin command, detailed
xref:documentation/payara-server/server-configuration/certificate-management.adoc#add-to-truststore[here].

[source,shell]
----
asadmin add-to-truststore --file mycert.crt mydomain_certificate
----

*Alternatively*::
You can also use the _keytool_ command of the JDK:

[source,shell]
----
keytool -importcert -trustcacerts -destkeystore cacerts.jks -file mycert.crt -alias mydomain_certificate
----

=== Update HTTP Listener

The last step we need to perform is the indication which 'certificate' needs to be used when Payara receives an SSL/TLS request. This can be done by specifying the alias name we have used when we integrated the required information into the key store files of the domain.

This information can be set either via the CLI,

[source,shell]
----
asadmin set configs.config.server-config.network-config.protocols.protocol.http-listener-2.ssl.cert-nickname=mydomain_certificate
----

In a default installation, the _http-listener-2_ is responsible for handling the secure connections on port 8181. The above command sets the alias name so that the system knows which certificate needs to be used.

The information can also be entered in the Web Administration console, by navigating to the page Configurations -> server-config -> HTTP Service -> HTTP Listeners > http-listener-2.

[certificate-expiration]
== Certificate expiration

All the X.509 certificates have a validity period when they can be used. Once this validity period is passed, the users will see a warning or error message depending on the browser that the certificate is no longer valid.

Within the server log file, the expired certificates are listed when the system encounters one. Besides your custom certificates which are added as described in a previous chapter, the Trust Store also contains certificates from the Certificate Authorities. Also, they can expire and thus can be listed in the log.

_Since Payara Server 5.20.0_

If you wish to remove all expired certificates, you can use the `remove-expired-certificates`, `remove-from-keystore`,
or `remove-from-truststore` commands detailed
xref:documentation/payara-server/server-configuration/certificate-management.adoc#remove-expired-certificates[here],
xref:documentation/payara-server/server-configuration/certificate-management.adoc#remove-from-keystore[here], and
xref:documentation/payara-server/server-configuration/certificate-management.adoc#remove-from-truststore[here] respectively.

[source,shell]
----
asadmin remove-expired-certificates
asadmin remove-from-keystore mydomain_certificate
asadmin remove-from-truststore mydomain_certificate
----

_Since Payara Server 5.194_

Since Payara Server 5.194 the log level of the expired certificates is of type WARNING. In previous versions, the entries showed as an ERROR. 

Since the server continues to operate normally, it was decided to lower the level of the message.


