[[maven-support]]
= Maven Support

This section describes Apache Maven support for Payara Micro.

[[artifacts-in-maven-central]]
== Artifacts in Maven Central

Payara Micro Enterprise has been uploaded to Maven Central, allowing you to include
it as a dependency in your POM.

This allows you to easily add the required Payara Micro classes and
methods to your application to use Payara Micro Enterprise programmatically.

In your project's POM, include the following dependency:

[source, xml]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-micro</artifactId>
    <version>${payara.version}</version>
</dependency>
----

`${payara.version}` is a Maven property, which specifies the version of the Maven
artifact, e.g. {currentVersion}.

[[public-api-reference]]
=== Public API Reference

_Since Payara Micro 4.1.1.171_

Starting from this release, you need to add a dependency to
the xref:/documentation/payara-server/public-api/README.adoc[Public API]
when developing applications that use proprietary features (`@Clustered` or
`@NamedCache` for example)

[[run-payara-micro-using-the-maven-plugin]]
== Run Payara Micro using the Maven Plugin

There is a maven plugin built specifically for use with Payara Micro. It has
goals to `bundle` the application into an Uber JAR, `start` and `stop` Payara
Micro. This plugin is xref:/documentation/ecosystem/maven-plugin.adoc[fully
documented in the Ecosystem section.]

[[run-payara-micro-using-the-netbeans-ide]]
== Run Payara Micro using the NetBeans IDE

There is a xref:https://github.com/payara/ecosystem-netbeans-plugin/tree/master/payara.micro[NetBeans IDE plugin - payara.micro module]
built specifically for Payara Micro to create and manage the application actions (e.g run, reload & debug).
This plugin is xref:/documentation/ecosystem/netbeans-plugin/payara-micro.adoc[fully
documented in the Ecosystem - Payara Plugin section.]
