[[client-certificate-validator]]
= Client Certificate Custom Validations

_Since Payara Server 5.29.0_


By default, Payara checks only if the submitted Client Certificate is present in the trust store. If it is found, it is accepted without any additional checks.

Since Payara 5.29.0, you can now implement a Client Certificate Validator which performs additional checks in addition to the presence of the certificate in the trust store.  You can perform a check on the validity date, use the Online Certificate Status Protocol (OCSP) to validate the certificate when it has a Certificate Revocation List entry (CRL), or lookup the DN name in a database for example, and determine based on this information if the certificate is still accepted.

When you want to implement custom validation, implement the `fish.payara.security.client.ClientCertificateValidator` interface and define your class through the ServiceLoader mechanism.

== Creating Custom Validation.

To have the `ClientCertificateValidator` interface available in your application, add the `payara-api` artifact to your application with the provided scope.


[source, xml]
----
        <dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-api</artifactId>
            <version>{currentVersion}</version>
            <scope>provided</scope>
        </dependency>
----

Now that you have the interface available, you can implement it in your application.

[source, java]
----
public class MyCertificateValidator implements ClientCertificateValidator {


    @Override
    public boolean isValid(Subject subject, X500Principal principal, X509Certificate certificate) {
         //
         return ...
    }
----

The most important parameter here is the `principal` parameter which contains the user information contained in the Client Certificate presented in the request.  The Certificate itself is in the last parameter and in the case you like to have access already to the `Subject` for this validation, it is passed in as the first parameter.

When you return `true` as the method result, the processing of the request continues. In the case false is returned, a `LoginException` is thrown resulting in a status 401 for the request.

This class is loaded through the Java ServiceLoader mechanism. Make sure you have the following file. _META-INF/services/fish.payara.security.client.ClientCertificateValidator_ containing the fully qualified name of your implementation.

----
com.company.certificate.MyCertificateValidator
----

NOTE: Since the class is loaded through the Java ServiceLoader mechanism, you cannot inject CDI or EJB beans into it. You can retrieve an instance of a CDI bean using  `CDI.current().select(MyCDIBean.class).get()`.  When the tenant Control code available in Payara Community is stabilised, it will be possible to directly inject those beans.
