= Supported Platforms

Though it is always possible for new versions to be supported, this page
details the JVMs currently supported by the Payara Platform Enterprise (both Payara Server Enterprise and Payara Micro Enterprise).

While not all environments are tested, if it is on a supported JVM we will
provide support for customers and address issues reported by the community.
Similarly, other platforms can always be requested for support.

== Supported Java Virtual Machines

The Payara Platform currently supports the following Java Virtual Machines:

* Oracle JDK8 (u162+), Oracle JDK 11 (11.0.5+)
* Azul Zulu JDK8 (u162+), Azul Zulu JDK 11 (11.0.5u10+)
* OpenJDK JDK8 (u162+), OpenJDK 11 (11.0.5+)
* All other JVMs based on OpenJDK 8u162+ or 11.0.5+ (for example Corretto JDK, Liberica JDK, AdoptOpenJDK)

TLS 1.3 is supported on JDK 8 with Azul Zulu 1.8.222+, Open JDK 8u262+ based builds, and all JDK 11 versions.

NOTE: A separate Payara Server Blue distribution is no longer required for IBM Java SDK.

== Supported Operating Systems

The Payara Platform currently supports the following Operating Systems in all the versions listed below and all their newer versions:

* Windows
** Windows 7+
** Windows Server 2008+
* Linux
** Ubuntu 14.04 (Trusty Tahr) LTS+
** Debian 7 (Wheezy)+
** CentOS 6+
** RHEL 5+
** OpenSUSE 42.2+
** SUSE 11.4, 12.2+, 15.0+
* Other
** MacOS(OSX) 10.10.5 (Yosemite)+
** IBM AIX 7.1+ 
