[[upgrade-server]]
= Upgrade Payara Server

__Since Payara Platform 5.24.0. Can be installed manually to Payara Platform 5.20.0 and newer._

This tool can be used to upgrade a Payara Server installation to a newer version. The Upgrade Tool is bundled in Payara Server versions from version *5.24.0*. It can also be obtained from Payara Nexus as the https://nexus.payara.fish/#browse/browse:payara-enterprise:fish%2Fpayara%2Fextras%2Fpayara-upgrade-tool[payara-upgrade-tool artifact] (groupId: `fish.payara.extras`, artifactId: `payara-upgrade-tool`). If obtained from the Payara Nexus, drop the JAR artifact into your Payara Server installation under `payara5/glassfish/lib/asadmin`. The version 1.0 of the standalone upgrade tool can be installed into Payara Server Enterprise 5.20.0 or newer and supports upgrading to any newer Payara Server Enterprise version.

[[upgrade-server-command]]
== Upgrade Server Command

*Usage*::
`asadmin> upgrade-server`

*Aim*::
This command can be used to upgrade Payara Server to the specified distribution along with all SSH nodes in the _domain.xml_.
The command will also back up the old version and domains in the default location (_payara5/glassfish/domains_) or the location specified using the `--domaindir` option to allow for rolling back. The command can also be used to downgrade to an older Payara version although this is not encouraged.

[[command-options-1]]
=== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--username` |String | The username for the Payara Nexus server.||Yes, unless `--usedownloaded` is specified
|`--version` |String |Specifies the version number of the new version of Payara to use.| |Yes, unless `--usedownloaded` is specified
|`--distribution` |Enum |Specifies the distribution of Payara Server to download. This can payara, payara-web, payara-ml, or payara-web-ml.|payara|No
|`--stage` |Boolean |Determines if the upgrade should be installed in-place, or staged into "_x.new_" directories. Scripts are provided that can be used to apply and rollback the staged install. This option is automatically enabled when running the command on Windows. |False on Unix, True on Windows| No
|`--domaindir` |String |The directory containing the domains. The domains in this directory are backed up, and their config is used to determine the nodes which will also be upgraded. | ${as-install}/domains | No
|`--usedownloaded` |String |The path to the local Payara Server zip archive to use for upgrading instead of downloading from the Payara Enterprise repository. When this parameter is specified, the `--username`, `--password`, and `--version` parameters are not required.| |No
|=======================================================================

[[upgrade-example]]
=== Example

This example upgrades a Payara Web distribution to version 5.24.1

[source, shell]
----
asadmin> upgrade-server --username example-user --distribution web --version 5.24.1
----

[[rollback-server-command]]
== Rollback Server Command

*Usage*::
`asadmin> rollback-server`

*Aim*::
This command can be used to rollback Payara Server to the point before the upgrade-server command was run, restoring the most recent backup of the domain (expected to be the backup created during execution of the `upgrade-server` command).

CAUTION: This command is not supported on Windows, please use the rollbackUpgrade.bat script.

[[command-options-2]]
=== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--domaindir` |String |The directory containing the domains. The domains in this directory are backed up, and their config is used to determine the nodes which will also be upgraded. | ${as-install}/domains | No
|=======================================================================

[[staged-upgrades]]
== Staged Upgrades

When the `upgrade-server` command is used on Windows, or with the `--stage` option enabled, the new server install is installed next to the current one in various _.new_ directories (e.g. `payara5/glassfish/bin.new`).


[[apply-staged-upgrades]]
=== Apply Staged Upgrade Script

*Usage*::
`> ./payara5/glassfish/bin/applyStagedUpgrade`

*Aim*::
This script is used to apply an upgrade staged using the `upgrade-server` command.
It will move the current installation into _.old_ directories, and the staged _.new_ installation into the expected "current" location.
It will then upgrade the nodes of the domains in the default domain dir, or the domains in the directory provided using `--domaindir`

[[command-options-3]]
==== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--domaindir` |String |The directory containing the domains. The config of the domains in this directory are used to determine the nodes which will also be upgraded. | ${as-install}/domains | No
|=======================================================================

[[rollback-upgrade-script]]
=== Rollback Upgrade Script

*Usage*::
`> ./payara5/glassfish/bin/rollbackUpgrade`

*Aim*::
This script is used to rollback a server upgrade applied using the `applyStagedUpgrade` script.
It will move the _.old_ installation back into the expected "current" location, and the applied upgrade back into _.new_ directories.
It will then rollback the nodes of the domains in the default domain dir, or the domains in the directory provided using `--domaindir`

[[command-options-3]]
==== Command Options

[cols=",,,,",options="header",]
|=======================================================================
|Option |Type |Description |Default |Mandatory
|`--domaindir` |String |The directory containing the domains. The config of the domains in this directory are used to determine the nodes which will also be rolled back. | ${as-install}/domains | No
|=======================================================================

[[cleanup-upgrade]]
=== Cleanup Upgrade Script

*Usage*::
`> ./payara5/glassfish/bin/cleanupUpgrade`

*Aim*::
This script is used to clean up any leftovers from a staged upgrade: any _.old_ folders and any _.new_ folders will be deleted.

CAUTION: Use of this script will prevent you from rolling back or applying a staged upgrade.

NOTE: This script cannot be used to clean up upgrades from releases prior to 5.26.0,
as it uses a config file to determine the directories to delete which is only generated by the `upgrade-server` command from 5.26.0 onwards.
