[[enhanced-ejb-features]]
= Enhancements to EJB Features

This section details several improvements and enhancements done to the EJB features available on Payara Server.

[[concurrent-instance-configuration]]
== Concurrent Instance Configuration

Payara Server Enterprise can control the number of maximum *concurrent* instances per EJB that can be served to clients. 

See xref:documentation/payara-server/ejb/concurrent-instances.adoc[Controlling Stateless EJB Concurrent Instances] for detailed information.

[[custom-ejb-jar-names]]
== Customized EJB-JAR Archive Names

It is possible to instruct Payara Server Enterprise to override the default behaviour of using the archive's filename as the name of the module at deployment time, even if the archive lives inside an EAR application.

See xref:documentation/payara-server/ejb/ejb-jar-names.adoc[Overwriting EJB JAR Archive Names] for detailed information.

[[lite-remote-ejb]]
== Lite Remote EJB Communication

For scenarios when communication with remote EJBs is needed across a complex network topology or when a server architecture is deployed on a cloud provider, there's a new feature for the EJB server and client applications: A lite and thin client that can be used to communicate via HTTP(S) instead of IIOP-RMI.

See xref:documentation/payara-server/ejb/lite-remote-ejb.adoc[Lite Remote EJB Communication] for detailed information.

[[persistent-timers]]
== Advanced Persistent Timer Configuration

If using an external RDBMS engine for storing persistent timer data is not an option, it is also possible to use the Domain Data Grid (introduced on Payara Server 5) to function as a replacement in production environments.

See xref:documentation/payara-server/ejb/persistent-timers.adoc[Persistent EJB Timers on the Domain Data Grid] for detailed information.

[[mbd-bean-pool-size]]
== Configuring MDB Bean Pool Size with ActivationConfigProperty
_Since Payara Server 5.193_

It is now possible to configure the MDB bean pool size with the `ActivationConfigProperty`.
Any Bean annotated with `@MessageDriven` can use `@ActivationConfigProperty` to set property names and property values. For Example;

	@ActivationConfigProperty(propertyName = ""MaxPoolSize"", propertyValue = "100")

`MaxPoolSize`, `MaxWaitTimeInMillis`, `PoolResizeQuantity`, `SteadyPoolSize` and `PoolIdleTimeoutInSeconds` are all MDB pool properties that can configured using `@ActivationConfigProperty`

