= Disable JLine Event Expansion

This feature disables using the Event Designators inside the Asadmin Multimode.

An https://www.gnu.org/software/bash/manual/html_node/Event-Designators.html[Event Designator] is a reference to a command line entry in the history list.

Event Designators are enabled by default. 

NOTE: If this feature is disabled, the `\` characters are not treated as escape characters when parsing the command and they are retained when running the command. The default behavior would treat them as escape characters and if you need to pass `\` into an asadmin command, you would need to escape it and turn it into `\\`. If event expansion is disabled, all `\` are passed to Payara Server without any change.

== Disabling JLine Event Expansion

Set the environment variable `+AS_ADMIN_DISABLE_EVENT_EXPANSION+` to `+false+` 

=== For Linux
. Open the Terminal
. Type the following command
+
----
export AS_ADMIN_DISABLE_EVENT_EXPANSION=false
----
+
. Check that the variable is set by typing the following command
+
----
echo $AS_ADMIN_DISABLE_EVENT_EXPANSION
----
+


=== For Windows
. Open Command Prompt as an Administrator
. Type the following commands
+
----
setx AS_ADMIN_DISABLE_EVENT_EXPANSION "false" /m
set AS_ADMIN_DISABLE_EVENT_EXPANSION=false
----
+
. Check that the variable is set by typing the following command
+
----
echo %AS_ADMIN_DISABLE_EVENT_EXPANSION%
----
+
