[[payara-server-command-reference]]
= Payara Server Management Asadmin Commands

This is a non-exhaustive list of asadmin commands which are exclusive to
Payara Server for managing domains.

[[start-domain]]
== `start-domain`

*Usage*::
`asadmin> start-domain <options> <domain>`

*Aim*::
This command start the specified domain

[cols="2,1,4,1,1",options="header"]
|===
|Options | Type | Description | Default | Mandatory

| verbose
| boolean
| starts the domain in verbose mode
| false
| No

| upgrade
| boolean
|
| false
| No

| watchdog
| boolean
|
| false
| No

| dry-run
| boolean
|
| false
| No

| drop-interrupted-commands
| boolean
|
| false
| No

| prebootcommandfile
| string
| path to file containing commands to run before booting the server. Only a limited amount of commands will work at this point. _Since Payara Server 4.1.2.172_
|
| No

| postbootcommandfile
| String
| path to file containg commands to run after the server is booted. _Since Payara Server 4.1.2.172_
|
| No

|===

[[start-domains]]
== `start-domains`

_Since Payara Server 4.1.2.173_

*Usage*::
`asadmin> start-domains <list of domains>`

*Aim*::
This command can be used to start the specified list of domains in the operand.
This list must be specified as a comma separated string of values.

NOTE: The domains will be started assuming default values for all options you would
specify when running the `start-domain` command against one domain (default domain directory,
debug mode off, verbose mode off, etc.)

[[command-options]]
=== Command Options

No command options available.

[[example]]
=== Example

To start the `domain1` and `production` domains, run the following command:

[source]
----
asadmin> start-domains domain1, production
----

[[stop-domains]]
== `stop-domains`

_Since Payara Server 4.1.2.173_

*Usage*::
`asadmin> stop-domains <list of domains>`

*Aim*::
This command can be used to stop the specified list of domains in the operand.
This list must be specified as a comma separated string of values.

NOTE: The domains will be stopped assuming default values for all options you would
specify when running the `stop-domain` command against one domain (forced stopping
 and process killing)

[[command-options-1]]
=== Command Options

No command options available.

[[example-1]]
=== Example

To stop the `domain1` and `production` domains, run the following command:

[source]
----
asadmin> stop-domains domain1, production
----

[[restart-domains]]
== `restart-domains`

_Since Payara Server 4.1.2.173_

*Usage*::
`asadmin> restart-domains <list of domains>`

*Aim*::
This command can be used to restart the specified list of domains in the operand.
This list must be specified as a comma separated string of values.

[[command-options-2]]
=== Command Options

No command options available.

[[example-2]]
=== Example

To restart the `domain1` and `production` , run the following command:


[source]
----
asadmin> restart-domains domain1, production
----

[[stop-all-domains]]
== `stop-all-domains`

*Usage*::
`asadmin> stop-all-domains`

*Aim*::
This command can be used to stop all running domains on the server installation.

[[command-options-5]]
=== Command Options

[cols="1,1,4,1,1",options="header",]
|====
|Option |Type |Description |Default |Mandatory
|`--force` |Boolean |Specifies whether each domain is forcibly stopped
immediately. |true |No
|`--kill` |Boolean |Specifies whether the domain is killed by using functionality
of the operating system to terminate the domain process |false |No
|====

[[example-5]]
=== Example

To forcibly stop all running domains, run the following command:

[source]
----
asadmin> stop-all-domains --force=false
----


[[start-instance]]
== `start-instance`

*Usage*::
`asadmin> start-instance instancename`

*Aim*::
This command can be used to start a specified instance of Payara, which can be either a local or remote instance. This command runs on the DAS.

[[command-options-4]]
=== Command Options

NOTE: These are not the same as the options for the `start-local-instance` command.

[cols="2,1,4,1,1",options="header",]
|====
|Option |Type |Description |Default |Mandatory
|`--sync` | none, normal or full |Specifies whether the instance is to be synced with the DAS. In normal mode only config files and top-level application file are synched. In full all files are synced. | normal |No
|`--debug` |Boolean |Specifies whether the instance is started in debug mode |false |No
|`--terse` |Boolean |Specifies whether information on the result is output |false |No
|`--timeout` |Integer |Specifies how long to take for the instance to start in seconds. If starting the instance takes longer than this amount then this command will fail. Available since 4.1.2.181 |120 |No
|====

WARNING: Using full sync will cause the configuration to be deleted if the DAS cannot be reached.

[[example-4]]
=== Example

To start an instance named instance1 and sync it with the DAS with a timeout of 180 seconds:

[source]
----
asadmin> start-instance --timeout 180 --sync true instance1
----

[[start-local-instance]]
== `start-local-instance`

*Usage*::
`asadmin> start-local-instance instancename`

*Aim*::
This command can be used to start a specified instance of Payara, but only when it corresponds to a local instance. A local instance is located in the same host from where the `asadmin` command is executed. This command is executed in "local" mode, which means that the DAS is not started in order to effectively execute it. Keep in mind that running the instance using the `sync` option has some nuances, so read the note below for more information.

[[command-options-3]]
=== Command Options

NOTE: These are not the same as the options for the `start-instance` command.


Usage: asadmin [asadmin-utility-options] start-local-instance


[cols="1,1,4,1,1",options="header",]
|====
|Option |Type |Description |Default |Mandatory
|`-v, --verbose` | Boolean |Specifies that the server log is printed to the console from which asadmin is executed. Control is not returned to the console after the instance has started. The instance can be stopped and control returned by typing `CTRL-C`. | false |No
|`-w, --watchdog` | Boolean |Starts the server in watchdog mode. This is only useful if verbose is false. It does the same thing as verbose -- except without the dumping of output to standard out and err streams.| false |No
|`-d, --debug` |Boolean |Specifies whether the instance is started in debug mode |false |No
|`-n, --dry-run` |Boolean | Specifies to dump the full human readable JVM invocation command that would be used to launch the instance instead of actually launching it. |false |No
|`--sync` | none, normal or full |Specifies whether the instance is to be synced with the DAS. In normal mode only config files and top-level application file are synched. In full all files are synced. | normal |No
|`--nodedir` | String | Specifies the folder on the local filesystem where the node the instance is in resides. | ${PAYARA_INSTALL_DIR}/glassfish/nodes/. |No
|`--node` | String | Specifies the node the instance is in. | The single folder inside the `nodedir` directory, in the case that there's only a single folder. |No - if the node directory contains a single folder, Yes - otherwise
|`--timeout` |Integer |Specifies how long to take for the local instance to start in seconds. If starting the instance takes longer than this amount then this command will fail (but the instance may still continue its startup process...). Available since 4.1.2.191.3 and 5.192 |600 |No
|====

WARNING: Using full sync will cause the configuration to be deleted if the DAS cannot be reached.

[[example-3]]
=== Example

To start a local instance named instance1 with a timeout of 180 seconds:

[source]
----
asadmin> start-local-instance --timeout 180 instance1
----

