= Arquillian Containers

:previewVersion: 5.181
include::partial$tech-preview.adoc[]

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara.

In version {currentVersion}, there are containers available for the following distributions:

* xref:documentation/ecosystem/arquillian-containers/payara-micro-managed.adoc[Payara Micro Managed]
* xref:documentation/ecosystem/arquillian-containers/payara-server-remote.adoc[Payara Server Remote]
* xref:documentation/ecosystem/arquillian-containers/payara-server-managed.adoc[Payara Server Managed]
* xref:documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc[Payara Server Embedded]

== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----

Some containers will be either in development or an early release version. In these cases
the same process can be used, but the artifact will need to be built from source.
The containers can be found in the main Payara source.

Clone the xref:https://github.com/payara/Payara[Payara] Git repository:

[source,Shell]
----
git clone https://github.com/payara/Payara.git
----

Build and install:

[source,Shell]
----
cd Payara/
mvn clean install -DskipTests
----