[[asadmin-commands-password-aliases]]
= Asadmin Commands for Managing Password Aliases

The following is a detailed list of the administration commands that can be used
to interact and configure password aliases.

[[create-alias]]
== `create-password-alias`

*Usage*::
`asadmin> create-password-alias <alias-name>`

*Aim*::
Creates a new password alias using the provided name. The user is then prompted
to enter the associated password twice. Password Aliases can also be created
non-interactively using a password file.

[[command-options]]
=== Command Options

There are no options available.

[[example]]
=== Example

Running the command will display output similar to the example below:

[source, shell]
----
asadmin> create-password-alias example-alias-name
Enter the alias password>
Enter the alias password again>
Command create-password-alias executed successfully.
----

[[delete-alias]]
== `delete-password-alias`

*Usage*::
`asadmin> delete-password-alias <alias-name>`

*Aim*::
Deletes the specified password alias and password from the server.

[[command-options-1]]
=== Command Options

There are no options available.

[[example-1]]
=== Example

Running the command will display output similar to the example below:

[source, shell]
----
asadmin> delete-password-alias example-alias-name
Command delete-password-alias executed successfully.
----

[[list-aliases]]
== `list-password-aliases`

*Usage*::
`asadmin> list-password-aliases`

*Aim*::
Lists the password aliases for the domain.

[[command-options-2]]
=== Command Options

There are no options available.

[[example-2]]
=== Example

Running the command will display output similar to the example below:

[source, shell]
----
asadmin> list-password-aliases
example-alias-name
another-example-alias
Command list-password-aliases executed successfully.
----

[[update-alias]]
== `update-password-alias`

*Usage*::
`asadmin> update-password-alias <alias-name>`

*Aim*::
Updates the password associated with the given alias. Passwords can also be
updated non-interactively using a password file.

[[command-options-3]]
=== Command Options

There are no options available.

[[example-3]]
=== Example

[source, shell]
----
asadmin> update-password-alias example-alias-name
Enter the alias password>
Enter the alias password again>
Encrypted password for the alias example-alias-name updated successfully
Command update-password-alias executed successfully.
----
