[[gathered-data]]
= Gathered Data

[[what-information-is-sent]]
== What information is sent?

All versions of Payara return a limited amount of information about its
specific configuration. No sensitive data about your machine or specific usage
of Payara Server is sent to 0s or any member of the Payara Services team.

[[gathered-fields]]
== Gathered attributes

The following is the list of information attributes gathered by the Phone
Home serviceL

[cols=",",options="header",]
|=======================================================================
|Attribute |Example
|Payara Server Version |4.1.1.164 #badassfish
|Java Virtual Machine Version |1.8.0_121
|Domain Uptime |36500
|Number of nodes in the domain |1
|Number of instances in the domain |2
|Randomly generated UUID
|eaa6fe2c-2388-4aa7-fdcc-288c7b318ddfeaa6ef23-2388-4aa7-8dcc-288c7b318ddf
|=======================================================================

This is the only data which the phone home service gathers from your
system.

NOTE: The UUID is specific to the DAS and is randomly generated on
startup, so it is not machine specific.

[[changes-to-gathered-fields]]
== Changes to gathered attributes

The following is an historic list of changes made to the phone home service
and the information attributes that are gathered by the service if its needed
for auditing purposes:

* `4.1.1.162`: Initial implementation of the service.
* `4.1.1.164`: *UUID* added.

[[how-is-the-information-transferred]]
== How is the information transferred?

Gathered phone home data is sent via a `GET` request to
http://www.payara.fish/phonehome[this address]

[[what-is-the-data-used-for]]
== What is the data used for?

The phone home data is presently used to gather usage statistics
about Payara Server, such as how long users typically run instances, and
what versions they use.

Previously this could only be done at an extremely simple level from
downloads over time, giving us no idea how Payara Server is used beyond
specific interactions with contributors and customers which may not
accurately represent the state of our user base.

The phone home service was designed as a non-intrusive survey tool which
would only gather data specific to Payara and has no contact with any
running applications, or indeed anything on your machine other than the
mentioned attributes.

[[source-code]]
== Source Code

If needed, the source code for the phone home script is available to
https://github.com/payara/Payara/blob/master/nucleus/payara-modules/phonehome-bootstrap/src/main/java/fish/payara/nucleus/phonehome/PhoneHomeTask.java[view
on github].
