[[rest-endpoints]]
= REST Endpoint
MicroProfile Metrics specifies that all metrics are published at the endpoint `/metrics`. For both Payara Server and Payara Micro, this means that the endpoint can be found on the HTTP port (default `8080`). By visiting these endpoints in a browser, the Prometheus text format can be viewed directly.

[[metric-scopes]]
== Metric Scopes
The Metrics specification https://github.com/eclipse/microprofile-metrics/blob/{mpMetricsVersion}/spec/src/main/asciidoc/metrics_spec.adoc#scopes[defines three _Scopes_], **Base**, **Vendor** and **Application** which correspond to the following purposes:

**Base**::
Base metrics are mandatory for all implementations to provide. This is so that there is a predictable baseline of metrics which will be available on any MicroProfile implementation.
+
These metrics can be accessed under `/metrics/base`.

**Vendor**::
Vendor metrics are specific to each implementation and are intended to offer metrics which are unique to each vendor.
+
These metrics can be accessed under `/metrics/vendor`.

**Application**::
Application metrics are reserved for those metrics which are to be exposed from the application by using the developer API.
+
These metrics can be accessed under `/metrics/application`.

