= Payara Enterprise 5.27.0 Release Notes

== Supported APIs and Applications

* Java EE 8 Applications
* Jakarta EE 8
* MicroProfile 3.3

== New Feature

*   [FISH-370] - Teams Notification channel
*   [FISH-471] - Discord Notification Channel
*   [FISH-1064] - Asadmin to clear out old job executions of JBatch in all supported databases

== Improvement

*   [FISH-315] - Implement New Public Notifier API
*   [FISH-316] - Upgrade New Relic Notifier to Implement New Notifier API
*   [FISH-317] - Upgrade XMPP Notifier to Implement New Notifier API
*   [FISH-318] - Upgrade SNMP Notifier to Implement New Notifier API
*   [FISH-319] - Upgrade Slack Notifier to Implement New Notifier API
*   [FISH-320] - Remove Hipchat Notifier
*   [FISH-321] - Upgrade Datadog Notifier to Implement New Notifier API
*   [FISH-322] - Upgrade Email Notifier to Implement New Notifier API
*   [FISH-323] - Upgrade JMS Notifier to Implement New Notifier API
*   [FISH-324] - Upgrade Eventbus Notifier to Implement New Notifier API
*   [FISH-325] - Upgrade CDI Eventbus Notifier to Implement New Notifier API
*   [FISH-973] - Allow Upgrade Tool to use a pre-downloaded version of Payara
*   [FISH-1094] - (Community Contribution) Make Micro boot-time deployment more reliable
*   [FISH-1145] - Add Validation to Upgrade Tool Scripts to Help Prevent Incorrect Usage
*   [FISH-1171] - Make Enabled Parameter of set-healthcheck-configuration Command Optional
*   [FISH-1172] - Make Enabled Parameter of set-admin-audit-configuration Command Optional
*   [FISH-1186] - Support server-node Docker Image within Kubernetes
*   [FISH-1202] - Improve Behaviour When Encountering Issues Upgrading Nodes When Using Upgrade Tool

== Bug

*   [FISH-514] - Fix Inconsistent behaviour when a domain backup is created
*   [FISH-1014] - [Community Contribution] Variables in @DatasourceDefinition not applied to 'className'
*   [FISH-1158] - OpenAPI document creation failed when using @Schema annotation with Enum missing a nullcheck
*   [FISH-1173] - Fix NullPointerException on Boot
*   [FISH-1174] - Fix NoSuchFileException When Upgrading Payara-Web
*   [FISH-1177] - Undeploy servlet NPE race condition
*   [FISH-1181] - Fix Conflicting --port Parameters in set-snmp-notifier-configuration/notification-snmp-configure Command
*   [FISH-1182] - Fix Conflicting --port Parameters in set-xmpp-notifier-configuration/notification-xmpp-configure Command
*   [FISH-1184] - Resolve DirectoryNotEmptyExceptions Thrown When Rolling Back Failed Upgrade