= Payara Enterprise 5.23.1 Release Notes

== Supported APIs and Applications

* Java EE 8 Applications
* MicroProfile 3.3
* Jakarta EE 8 Applications


== Improvements

* [FISH-152] - Mark applications as "unavailable" as soon as they are disabled 
* [FISH-520] - InSight QOL: Add Warning Icon to Confirmation Dialogs 
* [FISH-521] - InSight QOL: Adjust Used Font Sizes for More Consistent User Experience 
* [FISH-522] - InSight QOL: Improve the Flow of Newly Created Pages 
* [FISH-523] - InSight QOL: Renaming a Watch should not leave Watch with old name behind 
* [FISH-651] - Allow JWT verification to skip type validation 
* [FISH-732] - Improve message when same name is used in metrics.xml for exposed AMX bean. 
* [FISH-752] - Payara InSight: Aggregated History (sliding windows) 

== Bug Fixes

* [FISH-68] - @DatasourceDefinition not picking MicroProfile Configuration properties 
* [FISH-206] - @RolesAllowed annotation in method prevents unauthenticated calls to other methods in remote EJB 
* [FISH-275] - Deployment fails if system properties in persistence.xml are only defined in the target config and not in DAS config 
* [FISH-657] - no <deploymentgroup> element When deploy WebServices 
* [FISH-761] - [Community - bjetal] Deployment of unpacked WAB fails when using Felix fileinstall 
* [FISH-763] - [Community - sgflt] Embedded Payara is unable to start 
* [FISH-767] - Missing ejb-opentracing.jar in manifest of gf-client.jar 
* [FISH-777] - [Community - avpinchuk] Exclude OpenAPI rest endpoint from tracing 


== Component Upgrades

* [FISH-755] - Payara InSight 1.7 (API 1.2) 


