== Supported APIs and Applications

* Java EE 8 Applications
* MicroProfile 3.3
* Jakarta EE 8 Applications

*Notes*

In Payara Enterprise 5.21.0 (released in July), we added HTTP/2 support for JDK Native ALPN APIs. Unfortunately, we determined it has the potential for becoming unstable in certain situations. To maintain security and stability for all Enterprise customers in any situation - we've removed it from our Enterprise Editions until it's matured further. Reverting HTTP/2 support to how it worked in Payara Enterprise 5.20.0  means it will currently not work when using JDK 8u252 or higher (including JDK 11).

You may continue using HTTP/2 with an older supported version of JDK 8 (8u162-8u242). We will re-add HTTP/2 support for JDK Native ALPN APIs to Payara Enterprise in a future release after it’s deemed stable.

*Security Improvements*

* [FISH-381] - Upgrade Nimbus JOSE+JWT to 8.20

*Bug Fixes*

* [FISH-37] - @DataSourceDefinition passes serverName and URL DataSource in some cases
* [FISH-55] - Creating Java Mail Session targeted to Deployment Group fails
* [FISH-59] - Payara Micro --enableRequestTracing argument not accepting values
* [FISH-66] - Zip file closed on EJB initialization
* [FISH-82] - Command Line option --warmup results in an Exception when Payara Micro instance stops when Request Tracing is activated
* [FISH-89] - Possible NPE in request tracing during startup
* [FISH-90] - wscompile NoClassDefFoundError with JDK8
* [FISH-379] - Admin Console Masthead Looks Different Between Firefox and Chrome
* [FISH-388] - Fix NPE when printing out Active Span
* [FISH-393] - asadmin command list-rest-endpoints doesn't list PATCH methods
* [FISH-407] - List of enabled application targets is not always correct
* [FISH-425] - Revert FISH-31 - HTTP/2 Support for JDK Native ALPN APIs
