= Payara Enterprise 5.22 Release Notes

== Supported APIs and Applications

* Java EE 8 Applications
* MicroProfile 3.3
* Jakarta EE 8 Applications


== New Features

* [FISH-244] - Expand OpenTracing Support across Remote EJB Calls
* [FISH-277] - Payara InSight Integration
* FISH-433] - OpenID Connect session timeout association with access and/or identity token
expiry

== Improvements

* [FISH-141] - Support
Additional Fields with LogRecord when using JsonLogFormatter
* [FISH-154] - Support log-jdbc-calls attribute in xml used by asadmin commands
create-jdbc-connection-pool and add-resources (through xml)
* [FISH-389] - Add Transaction ID as a Baggage Item to Spans
* [FISH-426] - Store initial request path when accessing protected resource with
OpenIdAuthenticationMechanism
* [FISH-435] - Icons Integration
* [FISH-441] - StatsProviderManagerDelegate should write warning instead of throwing
Exception when stats provider info is not found.
* [FISH-449] - Oracle 19C Not Autodetected by EclipseLink
* [FISH-459] - Cleanup of sonar warnings in jdbc40 module

== Bug Fixes

* [FISH-25] - SOAP Web Service Tester not working correctly (JDK 11)
* [FISH-53] - Using Span.finish() doesn't finish a Propagated Span
* [FISH-93] - wsgen NoClassDefFoundError with jdk 11
* [FISH-196] - EJB injection in EJB Stateless based JAX-RS resource doesn't work in EAR.
* [FISH-198] - IllegalArgumentException on accessing the deploy asadmin REST endpoint
with upload flag
* [FISH-392] - Trace gets started even when RequestTracing is disabled.
* [FISH-396] - When _JAVA_OPTIONS specified, Payara Server incorrectly detects Java version
for JVM options
* [FISH-446] - [Community Contribution: https://github.com/svendiedrichsen[*svendiedrichsen*]]
Access to /metrics endpoint may cause ConcurrentModificationException
* [FISH-447] - TCK Failure Websocket module. Relates to HTTP2
* [FISH-474] - Admin Console doesn't display JDK distribution specified for a JVM option
* [FISH-477] - Deployment Group Properties are Ignored
* [FISH-509] - Deployment
failure due to 'The lifecycle method [postConstruct] must not throw a
checked exception.'

== Component Upgrades

* [FISH-604] - EclipseLink 2.7.7


