= Payara Enterprise 5.28.1 Release Notes

== Supported APIs and Applications

 * Java EE 8 Applications
 * Jakarta EE 8
 * MicroProfile 3.3

== Notes

=== Incompatibility with the latest JVM / JDK versions and Monitoring
IMPORTANT: Due to removal of SSL/TLS 1.0 and 1.1 protocols in the latest OpenJDK versions, monitoring data will not be available on JDK 8u292 and 11.0.11 or later because the JMX service fails to start and will not produce monitoring data. Other issues due to the missing protocols may also be present.

=== Improvement
* [FISH-1315] - (Community Contribution - https://github.com/AngelTG2[AngelTG2]) Improve loading time for REST application when there are many password aliases

=== Bug Fixes
* [FISH-1364] - Stale logs propagate between threads
* [FISH-1362] - Logging throws an exception when using number formatting
* [FISH-1328] - Concurrent Impl NPE w/Request Tracing
* [FISH-1327] - Unable to disable Wrap JDBC Objects using both the Admin Console or the asadmin command
* [FISH-52] - Remove reflective access for ENV variable replacement in Logging properties

=== Component Upgrade
* [FISH-1374] - Upgrade SnakeYaml
* [FISH-1347] - Upgrade commons-io

