== Supported APIs and Applications

* Java EE 8 Applications
* MicroProfile 3.3
* Jakarta EE 8 Applications

== Improvements

* [FISH-31] - HTTP/2 Support for JDK Native ALPN APIs
* [FISH-148] - Support multirelease JARs in WARs
* [FISH-151] - Implement MicroProfile JWT-Auth 1.1.1
* [FISH-171] - Support for multi HTTPAuthenticationMechanism
* [FISH-185] - Add set-network-listener-security-configuration Command
* [FISH-186] - Admin Console Integration for Certificate Management
* [FISH-187] - Make domain_name Parameter domainname in Cert Management Commands
* [FISH-189] - Add Warning when Adding to Certificate to the Keystore
* [FISH-191] - Add Additional Help Text to Cert Management Commands
* [FISH-192] - Add --reload Parameter to Certificate Management Commands
* [FISH-205] - Allow dynamic reconfiguration of log levels for Payara Micro instance
* [FISH-208] - Improvements in stop-domain process
* [FISH-219] - Indicate missing default value when using custom template for create-domain

== Bug Fixes

* [FISH-188] - Fix Adding PEMs with Add-to-keystore and Add-to-truststore Commands
* [FISH-190] - Missing Help Text for Certificate Management Commands
* [FISH-195] - Missing --nodedir and --node Options on Certificate Management Commands
* [FISH-197] - JDBCRealm requires the Message Digest field although a default value should be used
* [FISH-200] - generate-self-signed-certificate places a PrivateKeyEntry in the Truststore
* [FISH-207] - Disabling applications via their deployment group targets not working
* [FISH-211] - PayaraMicro APIs not initializable when run via RootLauncher
* [FISH-216] - Add-to-keystore and add-to-truststore Commands don't add CA signed certs correctly
* [FISH-236] - GitHub #4688 Typo in docker file - removal of /tmp/tmpfile
* [FISH-260] - Missing invocation on top of invocation stack
* [FISH-263] - Community Contribution: NPE when enabling versioned application with Microprofile Config

== Component Upgrades

* [FISH-243] - Update Monitoring Console Process to 1.2.1
