= Payara Micro Gradle Plugin

Payara Micro has a Gradle plugin which can start and stop Payara Micro and create
an Uber JAR bundle of the application and Payara Micro.

The plugin requires JDK 8 or higher and the latest version is currently `1.0.3`


== Installation
To use it, simply add the following script to your `build.gradle`:

```
plugins {
  id "fish.payara.micro-gradle-plugin" version "1.0.3"
}
```

=== Configuration Example:

```
payaraMicro {
    payaraVersion = '{currentVersion}'
    deployWar = false
    useUberJar = true
    daemon = false
    commandLineOptions = [port: 2468]
    javaCommandLineOptions = [Dtest: 'test123', ea:true] 
}
```

For more information, https://plugins.gradle.org/plugin/fish.payara.micro-gradle-plugin[click here].

== Plugin Tasks

=== `microBundle`
*Aim*: This task bundles the attached project's artifact into an Uber JAR with
the specified configurations.

*Usage*: `gradle microBundle`

.Configuration tags
[cols="2,1,7",options="header"]
|===
|Element
|Default
|Notes

|`javaPath`
|java
|Absolute path to the java executable..

|`payaraVersion`
|{currentVersion}
|By default `microBundle` task fetches payara-micro with version {currentVersion}.

|=== 

=== `microStart`
*Aim*: This task starts Payara Micro with the specified configuration.

*Usage*: `gradle microStart`

.Configuration tags
[cols="2,1,7",options="header"]
|===
|Element
|Default
|Notes

|`useUberJar`
|false
|Use created uber-jar that resides in target folder. The name of the JAR
artifact will be resolved automatically by evaluating its final name, artifact
ID and version. This configuration element has the higher precedence compared to
`payaraMicroAbsolutePath` and `payaraVersion`.

|`payaraMicroAbsolutePath`
|_none_
|Absolute path to payara-micro executable.

|`payaraVersion`
|{currentVersion}
|By default `microStart` task fetches payara-micro with version {currentVersion}.

|`daemon`
|false
|Starts payara-micro in separate JVM process and continues with the gradle build.

|`immediateExit`
|false
|If payara-micro is executed in daemon mode, the executor thread will wait for
the ready message before shutting down its process. By setting `immediateExit`
to `true` you can skip this and instantly interrupt the executor thread.

|`javaPath`
|`java`
|Absolute path to the java executable.

|`deployWar`
|false
|If the attached project is of type WAR, it will automatically be deployed to
payara-micro if `deployWar` is set to `true`.

|`javaCommandLineOptions`
|_none_
|Defines a list of command line options that will be passed to `java` executable.
Command line options can either be defined as key-value pairs or just as list of
values. key-value pairs will be formatted as `key=value`.

|`commandLineOptions`
|_none_
|Defines a list of command line options that will be passed onto payara-micro.


|===

=== `microStop`
*Aim*: This task stops Payara Micro with the specified configuration. 
By default this goal tries to find out currently executing payara-micro instance based on project GAV.
If `processId` is defined, it will take precedence and the given `processId` will
immediately kill the executing Payara Micro instance.

*Usage*: `gradle microStop`


.Configuration tags
[cols="2,1,7",options="header"]
|===
|Element
|Default
|Notes

|`processId`
|_none_
|Process id of the running payara-micro instance.

|`useUberJar`
| false
|Use created uber-jar that resides in build\libs folder. The name of the jar artifact will be resolved automatically by evaluating its final name.

|===
