= HTTP Options

The following HTTP fields can be configured for protocols:


[[configuration-http-server-name]]
== Server Name

The name of the server. This will be sent as the `Server` header in responses.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.server-name-enabled=value`

[[configuration-http-default-virtual-server]]
== Default Virtual Server

The default virtual server for the protocol. If multiple virtual servers are appropriate for a request,
this determines the priority.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.default-virtual-server=value`

[[configuration-http-redirect-port]]
== Redirect Port

The port used for SSL redirects.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.redirect-port=value`

[[configuration-http-max-connections]]
== Max Connections

The maximum number of requests per connection to keep in keep-alive mode.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.max-connections=value`

[[configuration-http-timeout]]
== Timeout

The amount of time in seconds before a connection is deemed as idle. After this, the connection will
no longer be in keep-alive state.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.timeout-seconds=value`

[[configuration-http-upload-timeout]]
== Upload Timeout Enabled

Enables closing a connection that is reading bytes slowly after the <<configuration-http-upload-timeout-millis>> is reached.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.upload-timeout-enabled=value`

[[configuration-http-upload-timeout-millis]]
== Connection Upload Timeout 

The timeout, in milliseconds, for uploads. A value of -1 will disable it.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.connection-upload-timeout-millis=value`

[[configuration-http-request-timeout]]
== Request Timeout

The timeout, in seconds, for requests. A value of -1 will disable it.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.request-timeout-seconds=value`

[[configuration-http-send-buffer-size]]
== Send Buffer Size

The size, in bytes, of the send buffer.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.send-buffer-size-bytes=value`

[[configuration-http-header-buffer-length]]
== Header Buffer Length

The size, in bytes, of the buffer used to read the request data.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.header-buffer-length-bytes=value`

[[configuration-http-max-post-size]]
== Max Post Size

The maximum size, in bytes, of POST actions.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.max-post-size-bytes=value`

[[configuration-http-max-form-post-size]]
== Max Form Post Size

The maximum size, in bytes, of a POST form.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.max-form-post-size-bytes=value`

[[configuration-http-max-save-post-size]]
== Max Save Post Size

The maximum size, in bytes, of a POST which will be saved during authentication.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.max-save-post-size-bytes=value`

[[configuration-http-uri-encoding]]
== URI Encoding

The character set used to decode the request URIs received.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.uri-encoding=value`

[[configuration-http-compression]]
== Compression

Whether to enable HTTP/1.1 GZIP compression to save server bandwidth. Will be ignored when HTTP/2 is used.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.compression=[off/on/force]`

[[configuration-http-compressable-mime-type]]
== Compressible Mime Types

Comma separated list of MIME types for which HTTP compression is used.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.compressable-mime-type=value`

[[configuration-http-compression-min-size]]
== Compression Minimum Size

The minimum size of a file when compression is applied.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.compression-min-size-bytes=value`

[[configuration-http-no-compression-user-agents]]
== No-Compression User Agents

Comma separated list of regular expressions matching user agents for which compression should not be used.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.no-compression-user-agents=value`

[[configuration-http-restricted-user-agents]]
== Restricted User Agents

List of restricted user agents for which HTTP compression is applied.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.restricted-user-agents=value`

[[configuration-http-default-response-type]]
== Default Response Type

The default response type if none are matched. Specified as a semi-colon delimited string consisting of
content type, encoding, language, charset.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.default-response-type=value`

[[configuration-http-adapter]]
== Adapter

The class name of the static resources adapter.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.adapter=value`

[[configuration-http-comet-support]]
== Comet Support

Whether comet support is enabled or not.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.comet-support-enabled=[true/false]`

[[configuration-http-dns-lookup]]
== DNS Lookup

Enables Domain Name System lookups.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.dns-lookup-enabled=[true/false]`

[[configuration-http-trace-operation]]
== Trace Enabled

Enables the TRACE operation. Setting this to false helps prevent cross-site scripting attacks.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.trace-enabled=[true/false]`

[[configuration-http-auth-pass-through]]
== Auth Pass Through

Enable this if the network listener receives traffic from an SSL terminating proxy server.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.auth-pass-through-enabled=[true/false]`

[[configuration-http-chunking-enabled]]
== Chunking Enabled

Enables HTTP response chunking.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.chunking-enabled=[true/false]`

[[configuration-http-xpowered-by]]
== XPoweredBy

Whether to include the X-Powered-By header in responses.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.xpowered-by=value`

[[configuration-http-xframe-options]]
== XFrame Options

When enabled, the X-Frame-Options header will be set to SAMEORIGIN. This can still be overrided by
a deployed application.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.xframe-options=value`

[[configuration-http-encoded-slash]]
== Encoded Slash

Allow encoded slashes (e.g. `%2F`) in URIs.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.encoded-slash-enabled=[true/false]`

[[configuration-http-websockets-support]]
== Websockets Support Enabled

Allows websockets to be used.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.websockets-support-enabled=[true/false]`

[[configuration-http-scheme-mapping]]
== Scheme Mapping

HTTP header name used for identifying the originating protocol of a HTTP request.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.scheme-mapping=value`

[[configuration-http-remote-user-mapping]]
== Remote User Mapping

HTTP header name used for identifying the originating user of a HTTP request.

*Asadmin Command:*

`set configs.config.server-config.network-config.protocols.protocol.${protocol-name}.http.remote-user-mapping=value`
